In [ ]:
incidence_matrix = zeros(Int32, 3, 3)

In [ ]:
bus1_idx = [1,3]
bus2_idx = [3,2]

for (bus1, bus2) in zip(bus1_idx, bus2_idx)
    incidence_matrix[bus1, bus2] = -1
    incidence_matrix[bus2, bus1] = 1
end

incidence_matrix

In [ ]:
function create_incidence_matrix(num_bus, num_line, bus1_idx, bus2_idx)
    # incidence_matrix = zeros(Int32, length(bus1_idx), length(bus1_idx))
    # for (bus1, bus2) in zip(bus1_idx, bus2_idx)
    #     incidence_matrix[bus1, bus2] = -1
    #     incidence_matrix[bus2, bus1] = 1
    # end
    # num_bus = length(bus1_idx)
    incidence_matrix = zeros(Int32, num_line, num_bus)
    line_idx = collect(1:num_line)

    for line in line_idx
        incidence_matrix[line, bus1_idx[line]] = 1
        incidence_matrix[line, bus2_idx[line]] = -1
    end
    
    return incidence_matrix
end

In [ ]:
## test multiple lines connected to the same bus


bus1_idx = [1,1,2,3,1]
bus2_idx = [2,4,4,4,3]

num_line = length(bus1_idx)
num_bus = 4


incidence_matrix = create_incidence_matrix(num_bus, num_line, bus1_idx, bus2_idx)

id = [0.5, 0.3, 0.9, -1.2, 0.0]

# i = @. incidence_matrix[bus1_idx,bus2_idx] * id





In [ ]:
incidence_matrix

In [ ]:
# case14

bus1_idx = [1, 1, 2, 2, 2, 3, 4, 6, 6, 6, 7, 9, 9, 10, 12, 13, 4, 4, 6, 8]
bus2_idx = [2, 5, 3, 4, 5, 4, 5, 11, 12, 13, 9, 10, 14, 11, 13, 14, 7, 9, 5, 7]

num_bus = 14
num_line = length(bus1_idx)

line_idx = collect(1:num_line)

incidence_matrix = create_incidence_matrix(bus1_idx, bus2_idx)

In [ ]:
incidence_matrix = zeros(Int32, num_line, num_bus)

for line in line_idx
    incidence_matrix[line, bus1_idx[line]] = 1
    incidence_matrix[line, bus2_idx[line]] = -1
end

incidence_matrix

In [ ]:
incidence_matrix = zeros(Int32, num_bus, num_line)


bus1_idx = [1,1,2,3,1]
bus2_idx = [2,4,4,4,3]

num_line = length(bus1_idx)
num_bus = 4

id = [0.5, 0.3, 0.9, -1.2, 0.0]

line_idx = collect(1:num_line)



for line in line_idx
    incidence_matrix[bus1_idx[line], line] = -1
    incidence_matrix[bus2_idx[line], line] = 1
end

incidence_matrix

In [ ]:
incidence_matrix * id

In [ ]:
bus1_idx = [1,1,3,2,2,5,6,4,4]
bus2_idx = [4,3,2,6,5,6,1,3,5]

num_line = length(bus1_idx)
num_bus = 6


incidence_matrix = zeros(Int32, num_bus, num_line)


id = [0.2, 0.9, 0.7, 1.2, 1.9, 0.1, 0.2, 3.0, 0.01]

@assert length(id) == num_line

line_idx = collect(1:num_line)

for line in line_idx
    incidence_matrix[bus1_idx[line], line] = -1
    incidence_matrix[bus2_idx[line], line] = 1
end

incidence_matrix

In [ ]:
incidence_matrix * id

In [ ]:
a_idx=[1,2,3]
b_idx = [3,1,2]


a_data = [10,20,30]
b_data = [30,10, 20]

c = zeros(3)
c_idx = a_idx[:]


a_map = Dict(Int32.(a_idx[r]) =>a_data[r] for r in eachrow(a_idx))
b_map = Dict(Int32.(b_idx[r]) =>b_data[r] for r in eachrow(b_idx))

# c_idx = a_idx[:]

# idx = 1
# for (i, j) in zip(a, b)
#     c[idx] = a_data[i]
# end

# c

In [ ]:
for (k,v) in a_map
    c[k] = v
end

In [ ]:
c_idx

In [ ]:
for i in 1:3
    c[i] = b_map[b_idx[i]]
end

In [ ]:
a_map = Dict(a_idx[r] => Float64.(a_data)[r] for r in eachrow(a_idx))
for (k,v) in a_map
    c[k] = v
end

In [ ]:
c

In [1]:
bus_idx = [1,2,3,4,5,6,7,8]
pq_bus = [1,5,3,6]
pv_bus = [1,2,4,5]
slack = [8]

1-element Vector{Int64}:
 8

In [3]:
non_gen_bus = setdiff(bus_idx, pv_bus, slack)

3-element Vector{Int64}:
 3
 6
 7

In [4]:
con_bus = setdiff(non_gen_bus, pq_bus)

1-element Vector{Int64}:
 7

In [5]:
load_bus = vcat(pq_bus, con_bus)

5-element Vector{Int64}:
 1
 5
 3
 6
 7

In [ ]:
bus1 = [1,2,3]
bus2 = [2,1,1]
r = [0.1, 0.2, 0.3]
x = [0.4, 0.5, 0.6]
b = [0.7, 0.8, 0.9]

for idx in length(bus1)
    if 

In [6]:
using XLSX, DataFrames, Base.Threads

In [12]:
data_file = "/Users/aali27/Work/repos/emt_simulator_basic/cases/SMIB_Chow/SMIB_RL_Line_DrCui.xlsx"

"/Users/aali27/Work/repos/emt_simulator_basic/cases/SMIB_Chow/SMIB_RL_Line_DrCui.xlsx"

In [13]:
isfile(data_file) || error("Case file not found: $data_file")

true

In [14]:
tables = Dict{Symbol, DataFrame}()

Dict{Symbol, DataFrame}()

In [18]:
_sym(s::AbstractString) = Symbol(lowercase(s))


_sym (generic function with 1 method)

In [19]:
XLSX.openxlsx(data_file) do xf
    sheet_names = XLSX.sheetnames(xf)
    for sheet in sheet_names
        ws = xf[sheet]
        df = DataFrame(XLSX.gettable(ws))
        tables[_sym(sheet)] = df
    end
end

In [20]:
tables

Dict{Symbol, DataFrame} with 10 entries:
  :line    => 2×27 DataFrame…
  :bus     => 3×14 DataFrame…
  :fault   => 1×9 DataFrame…
  :gencls  => 1×22 DataFrame…
  :shunt   => 1×10 DataFrame…
  :summary => 3×6 DataFrame…
  :pv      => 1×19 DataFrame…
  :slack   => 1×20 DataFrame…
  :pq      => 1×11 DataFrame…
  :area    => 1×4 DataFrame…

In [21]:
tables[:line]

Row,uid,idx,u,name,bus1,bus2,Sn,fn,Vn1,Vn2,r,x,b,g,b1,g1,b2,g2,trans,tap,phi,rate_a,rate_b,rate_c,owner,xcoord,ycoord
,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any,Any
1,0,1,1,Line 1,1,3,100,60,110,110,0.015,0.15,0,0,0,0,0,0,0,1,0,0,0,0,missing,missing,missing
2,1,2,1,Line 2,3,2,100,60,110,110,0.0198,0.198,0,0,0,0,0,0,0,1,0,0,0,0,missing,missing,missing


In [24]:
keys(tables)

KeySet for a Dict{Symbol, DataFrame} with 10 entries. Keys:
  :line
  :bus
  :fault
  :gencls
  :shunt
  :summary
  :pv
  :slack
  :pq
  :area

In [25]:
tables

Dict{Symbol, DataFrame} with 10 entries:
  :line    => 2×27 DataFrame…
  :bus     => 3×14 DataFrame…
  :fault   => 1×9 DataFrame…
  :gencls  => 1×22 DataFrame…
  :shunt   => 1×10 DataFrame…
  :summary => 3×6 DataFrame…
  :pv      => 1×19 DataFrame…
  :slack   => 1×20 DataFrame…
  :pq      => 1×11 DataFrame…
  :area    => 1×4 DataFrame…

In [ ]:
module DataLoader

export load_data, models_dict

using Pkg
Pkg.activate(".")

using XLSX
using DataFrames

include("Models.jl")
using .Models


models_dict = Dict{String, Any}()

function load_data(data_file::String)
    if isfile(data_file)
        xf = XLSX.readxlsx(data_file)

        for sheet in XLSX.sheetnames(xf)
            df = DataFrame(XLSX.readtable(data_file, sheet))
            if sheet == "Bus"
                bus = Bus{Float64}(length(df.idx))
                bus.idx = Int32.(df.idx)
                bus.v = Float64.(df.v0)
                bus.theta = Float64.(df.a0)
                bus.vd = zeros(Float64, length(df.idx))
                bus.vq = zeros(Float64, length(df.idx))
                # bus.i_d = zeros(Float64, length(df.idx))
                # bus.i_q = zeros(Float64, length(df.idx))
                models_dict["bus"] = bus
            end
            if sheet == "Line"
                line = Line{Float64}(length(df.idx))
                line.idx = Int32.(df.idx)
                line.bus1_idx = Int32.(df.bus1)
                line.bus2_idx = Int32.(df.bus2)
                # line.R = Float64.(max.(df.r, 1e-8))
                # line.X = Float64.(max.(df.x, 1e-8))
                line.R = Float64.(df.r)
                line.X = Float64.(df.x)
                line.i_d = zeros(Float64, length(df.idx))
                line.i_q = zeros(Float64, length(df.idx))
                models_dict["line"] = line
            end
            if sheet == "GENCLS" || sheet == "GENROU"
                generator = Generator{Float64}(length(df.idx))
                generator.idx = Int32.(df.idx)
                generator.bus = Int32.(df.bus)
                generator.delta = ones(Float64, length(df.idx))
                generator.omega = ones(Float64, length(df.idx))
                generator.M = Float64.(df.M)
                # generator.p_m = Float64.(df.p_m)
                generator.i_d = zeros(Float64, length(df.idx))
                generator.i_q = zeros(Float64, length(df.idx))
                generator.x_d_prime = Float64.(df.xd1)
                generator.e_q_prime = ones(Float64, length(df.idx))
        
                df_pv = DataFrame(XLSX.readtable(data_file, "PV"))
                generator.p_m = Float64.(df_pv.p0)
                generator.q_m = Float64.(df_pv.q0)
        
                models_dict["generator"] = generator
            end
        
            if sheet == "Fault"
                fault = Fault{Float64}(length(df.idx))
                fault.bus = Int32.(df.bus)
                fault.r_s = Float64.(df.rf)
                fault.l_s = Float64.(df.xf)
                # fault.i_d = zeros(Float64, length(df.idx))
                # fault.i_q = zeros(Float64, length(df.idx))
                fault.tf = Float64.(df.tf)
                fault.tc = Float64.(df.tc)
        
                models_dict["fault"] = fault
            end
            if sheet == "PQ"
                load = Load{Float64}(length(df.idx))
                load.bus = Int32.(df.bus)
                load.p = Float64.(df.p0)
                load.q = Float64.(df.q0)
        
                models_dict["load"] = load
            end
        
            if sheet == "Slack"
                slack = Slack(length(df.idx))
                slack.bus = Int32.(df.bus)
        
                models_dict["slack"] = slack
            end
        end

        return models_dict
    else
        error("File $data_file does not exist")
    end
end


end #module

In [33]:
bus1 = [1,3]
bus2 = [3,2]

B = [2, 1]

B_mat = zeros(ComplexF64, 3, 3)

idx = 1
for (bus1, bus2) in zip(bus1, bus2)
    B_mat[bus1, bus1] += 1im*B[idx] / 2
    B_mat[bus2, bus2] += 1im*B[idx] / 2
    idx += 1
end

B_mat

3×3 Matrix{ComplexF64}:
 0.0+1.0im  0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.5im  0.0+0.0im
 0.0+0.0im  0.0+0.0im  0.0+1.5im

In [34]:
abs.(B_mat)

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  0.5  0.0
 0.0  0.0  1.5